export const NAVBAR_COPY = {
  home: "Trang chủ",
  blog: "Blog",
  blogPosts: "Bài viết",
  courses: "Khóa học",
  community: "Cộng đồng",
  games: "Trò chơi",
  leaderboard: "Bảng xếp hạng",
  discussion: "Thảo luận",
  chatGroups: "Nhóm chat",
  about: "Về chúng tôi",
  intro: "Giới thiệu",
  contact: "Liên hệ",
  login: "Đăng nhập",
  logout: "Đăng xuất",
  profile: "Hồ sơ",
  admin: "Quản trị",
  dashboard: "Bảng điều khiển",
} as const;

export const AUTH_COPY = {
  login: {
    title: "Đăng nhập EDUcare",
    subtitle: "Chào mừng bạn quay lại với hành trình học tập và chăm sóc bản thân mỗi ngày.",
    identityLabel: "Email hoặc tên đăng nhập",
    passwordLabel: "Mật khẩu",
    passwordPlaceholder: "Nhập mật khẩu",
    submit: "Đăng nhập",
    loading: "Đang đăng nhập...",
    missingAccount: "Chưa có tài khoản?",
    register: "Đăng ký",
    forgotPassword: "Quên mật khẩu?",
    genericError: "Đã xảy ra lỗi.",
  },
  register: {
    title: "Tạo tài khoản EDUcare",
    subtitle: "Đăng ký miễn phí để bắt đầu học tập, theo dõi tiến độ và tham gia cộng đồng.",
    fullName: "Họ và tên",
    username: "Tên đăng nhập",
    password: "Mật khẩu",
    confirmPassword: "Xác nhận mật khẩu",
    age: "Độ tuổi",
    passwordPlaceholder: "Tạo mật khẩu",
    confirmPasswordPlaceholder: "Nhập lại mật khẩu",
    submit: "Đăng ký",
    loading: "Đang tạo tài khoản...",
    hasAccount: "Đã có tài khoản?",
    login: "Đăng nhập",
    passwordStrength: "Độ mạnh mật khẩu",
    passwordMismatch: "Mật khẩu xác nhận không khớp.",
    passwordTooShort: "Mật khẩu cần có ít nhất 6 ký tự.",
    invalidAge: "Độ tuổi hợp lệ từ 10 đến 20.",
    genericError: "Đã xảy ra lỗi.",
    strength: {
      weak: "Yếu",
      medium: "Trung bình",
      fair: "Khá",
      strong: "Mạnh",
    },
  },
  forgotPassword: {
    title: "Quên mật khẩu",
    subtitle: "Nhập email đã đăng ký để nhận mã đặt lại mật khẩu.",
    emailLabel: "Email",
    submit: "Gửi yêu cầu",
    loading: "Đang gửi...",
    backToLogin: "Quay lại đăng nhập",
    devHelp: "Nếu bạn thấy mã reset thì dán vào trang đặt lại mật khẩu hoặc bấm vào liên kết ngay bên dưới.",
    openResetPage: "Đặt lại mật khẩu ngay",
    genericError: "Đã xảy ra lỗi.",
  },
  resetPassword: {
    title: "Đặt lại mật khẩu",
    subtitle: "Nhập mã xác nhận và mật khẩu mới để hoàn tất.",
    tokenLabel: "Mã xác nhận",
    tokenPlaceholder: "Nhập mã xác nhận",
    password: "Mật khẩu mới",
    confirmPassword: "Xác nhận mật khẩu",
    passwordPlaceholder: "Nhập mật khẩu mới",
    confirmPasswordPlaceholder: "Nhập lại mật khẩu mới",
    submit: "Đặt lại mật khẩu",
    loading: "Đang cập nhật...",
    missingToken: "Vui lòng nhập mã xác nhận.",
    passwordMismatch: "Mật khẩu xác nhận không khớp.",
    passwordTooShort: "Mật khẩu cần có ít nhất 6 ký tự.",
    successMessage: "Mật khẩu đã được đặt lại. Vui lòng đăng nhập lại.",
    genericError: "Đã xảy ra lỗi.",
  },
} as const;

export const BLOG_COPY = {
  allCategory: "Tất cả",
  eyebrow: "Thư viện bài viết",
  titleLine1: "Hiểu mình vững hơn,",
  titleLine2: "lớn lên tích cực hơn.",
  description:
    "Những bài viết trên EDUcare giúp bạn hiểu cảm xúc, nuôi dưỡng sự tự tin, xây dựng kỹ năng sống và giữ cho hành trình trưởng thành trở nên lành mạnh, an toàn hơn mỗi ngày.",
  imageAlt: "Minh họa thư viện bài viết EDUcare",
  readAction: "Xem bài viết",
  listTitle: "Danh sách bài viết",
  listDescription: "Chọn chủ đề bạn đang quan tâm để đọc nhanh những nội dung phù hợp.",
  empty: "Chưa có bài viết phù hợp với chủ đề bạn đang chọn.",
  loadError: "Không thể tải danh sách bài viết.",
} as const;

export const GAMES_COPY = {
  eyebrow: "Khu trò chơi EDUcare",
  title: "Chơi nhẹ nhàng, tiến bộ rõ ràng.",
  description:
    "Chọn trò chơi phù hợp với tâm trạng và nhịp học của bạn. Mỗi trò đều giữ tinh thần tích cực, an toàn và gần gũi với tuổi teen.",
  playQuickQuiz: "Bắt đầu nhanh",
  viewLeaderboard: "Xem bảng xếp hạng",
  imageTopLeft: "Vui học theo cách riêng",
  imageTopRightSuffix: "trò chơi",
  imageAlt: "Minh họa khu trò chơi EDUcare",
  heroSteps: [
    "Chọn trò phù hợp với tâm trạng hiện tại",
    "Mở vào xem chi tiết trước khi chơi",
    "Theo dõi điểm số và tiến bộ của riêng bạn",
  ],
  sectionEyebrow: "Danh sách trò chơi",
  sectionTitle: "Chọn trò phù hợp rồi bắt đầu",
  sectionDescription: "Mỗi trò đều có trang riêng để bạn xem mục tiêu, cách chơi và bắt đầu thật rõ ràng.",
  openLeaderboard: "Mở trang bảng xếp hạng",
  playAction: "Xem chi tiết",
  cardHint: "Luật chơi và phần hướng dẫn sẽ hiển thị trong trang trò chơi.",
  loadError: "Không thể tải danh sách trò chơi.",
  flashBadge: "Mini game",
  longQuizBadge: "Quiz dài",
  quickQuizBadge: "Quiz nhanh",
} as const;

export const LEADERBOARD_COPY = {
  eyebrow: "Bảng xếp hạng cộng đồng",
  title: "Theo dõi streak và tổng điểm quiz của cộng đồng",
  description:
    "Bảng xếp hạng ưu tiên streak, sau đó đến tổng điểm quiz và XP để phản ánh sự đều đặn, nỗ lực và tiến bộ của mỗi người.",
  backToGames: "Quay lại khu trò chơi",
  toCommunity: "Sang khu thảo luận",
  stats: [
    { label: "Thành viên", getValue: (count: number) => `${count} người` },
    { label: "Trọng tâm", getValue: () => "Top streak" },
    { label: "Điểm nổi bật", getValue: () => "Tổng điểm quiz" },
  ],
  loading: "Đang tải bảng xếp hạng...",
  rankLabel: (rank: number) => `Hạng ${rank}`,
  currentStreak: "Streak hiện tại",
  totalQuizScore: "Tổng điểm quiz",
  fullListTitle: "Danh sách đầy đủ",
  fullListDescription: "Thứ hạng được sắp xếp theo streak, tổng điểm quiz và XP.",
  rankingGuideTitle: "Cách tính thứ hạng",
  rankingGuide: [
    "Streak được ưu tiên cao nhất vì thể hiện sự đều đặn trong học tập và tương tác.",
    "Tổng điểm quiz cho thấy mức độ tích lũy kiến thức sau nhiều lượt chơi.",
    "XP giúp phản ánh toàn bộ quá trình học tập và sử dụng hệ thống.",
  ],
  yourStats: "Thành tích của bạn",
  loginPrompt: "Đăng nhập để lưu điểm quiz, streak và theo dõi vị trí của bạn trên bảng xếp hạng.",
  loginNow: "Đăng nhập ngay",
  loadError: "Không thể tải bảng xếp hạng lúc này.",
} as const;

export const QUIZ_COPY = {
  modeLabel: {
    quick: "Quiz nhanh 10 câu",
    long: "Quiz dài 30 câu",
  },
  modeDescription: {
    quick: "Chế độ ngắn gọn với 10 câu ngẫu nhiên để kiểm tra nhanh kiến thức và phản xạ.",
    long: "Chế độ luyện sâu với 30 câu ngẫu nhiên để bạn hiểu kỹ chủ đề và cải thiện điểm số.",
  },
  loading: "Đang tải bộ câu hỏi quiz...",
  loadError: "Không thể tải bộ câu hỏi quiz.",
  finishAllAnswers: "Bạn cần trả lời hết trước khi nộp bài.",
  completeTurn: "Đã hoàn thành lượt quiz.",
  submitError: "Không thể nộp bài quiz.",
  currentRound: "Lượt chơi hiện tại",
  totalQuestions: "Tổng câu",
  answered: "Đã trả lời",
  mode: "Chế độ",
  deepPractice: "Luyện sâu",
  quickCompact: "Nhanh gọn",
  result: "Kết quả lượt chơi",
  correctAnswers: (correct: number, total: number) => `${correct}/${total} câu đúng`,
  roundScore: "Điểm lượt này",
  totalQuizScore: "Tổng điểm quiz",
  loginToSave: "Đăng nhập để lưu",
  streak: "Streak",
  notSaved: "Chưa lưu",
  replay: "Chơi lại chế độ này",
  switchTo: (mode: "quick" | "long") => `Chuyển sang ${mode === "quick" ? "quiz nhanh" : "quiz dài"}`,
  viewLeaderboard: "Xem bảng xếp hạng",
  savePrompt: "Đăng nhập để lưu điểm vào thành tích cá nhân và tiếp tục tăng streak sau mỗi lượt chơi.",
  quickReview: "Xem lại từng câu",
  correctAnswer: "Bạn đã trả lời đúng.",
  incorrectAnswer: "Bạn đã trả lời chưa đúng.",
  question: (index: number) => `Câu hỏi ${index}`,
  previousQuestion: "Câu trước",
  nextQuestion: "Câu tiếp",
  submitting: "Đang nộp bài...",
  finishRound: "Hoàn tất lượt chơi",
  progress: "Tiến độ",
  questionList: "Danh sách câu",
  otherMode: "Chế độ khác",
} as const;

export const FLASH_GAME_COPY = {
  eyebrow: "Mini game flash style",
  title: "Ánh sáng tự tin",
  description:
    "Điều khiển nhân vật thu thập các điểm sáng tích cực và tránh đám mây lo âu. Đây là một trò chơi ngắn, vui và bám đúng chủ đề xây dựng sự tự tin cho tuổi teen.",
  controls: "Điều khiển",
  controlsValue: "WASD hoặc mũi tên",
  time: "Thời gian",
  seconds: "giây",
  score: "Điểm hiện tại",
  gameOver: "Kết thúc lượt chơi",
  playAgain: "Chơi lại",
  backToGames: "Quay lại khu trò chơi",
  objective: "Mục tiêu",
  objectiveTitle: "Thu thập điểm sáng tích cực",
  objectiveDescription:
    "Chạy vào điểm sáng để cộng điểm, né đám mây lo âu để tránh mất điểm và cố gắng giữ nhịp di chuyển ổn định trong suốt lượt chơi.",
  quickRating: "Đánh giá nhanh",
  timeRemaining: "Thời gian còn lại",
  status: "Trạng thái",
  playing: "Đang chơi",
  ended: "Đã kết thúc",
  scoreLabels: {
    high: "Tỏa sáng rất tốt",
    good: "Đang lên rất ổn",
    medium: "Bạn đang bắt nhịp",
    low: "Thử thêm một lượt nữa",
  },
} as const;

export const DASHBOARD_COPY = {
  loading: "Đang tải bảng điều khiển...",
  loadError: "Không thể tải bảng điều khiển.",
  eyebrow: "Khu vực học tập cá nhân",
  greeting: "Xin chào",
  description:
    "Theo dõi tiến độ học tập, bài học tiếp theo, thành tích gần đây và các thông báo quan trọng dành cho bạn.",
  stats: {
    streak: "Chuỗi ngày",
    lessons: "Bài học",
    plan: "Gói",
  },
  courseProgress: "Tiến độ khóa học",
  nextLesson: "Bài học tiếp theo",
  freeLesson: "Bài học miễn phí",
  paidLesson: "Dành cho gói Phổ biến hoặc Cao cấp",
  recentCompleted: "Hoàn thành gần đây",
  noRecentCompleted: "Chưa có bài học nào được hoàn thành.",
  completed: "Đã hoàn thành",
  notifications: "Thông báo",
  noNotifications: "Chưa có thông báo nào lúc này.",
  quickLinks: [
    { label: "Khóa học", to: "/courses" },
    { label: "Trò chơi", to: "/games" },
    { label: "Bài viết", to: "/blog" },
    { label: "Cộng đồng", to: "/community" },
  ],
  planLabels: {
    free: "Miễn phí",
    popular: "Phổ biến",
    premium: "Cao cấp",
  },
  notificationTypes: {
    system: "Hệ thống",
    lesson: "Bài học",
    community: "Cộng đồng",
  },
} as const;

export const ADMIN_COPY = {
  loading: "Đang tải bảng điều khiển quản trị...",
  loadError: "Không thể tải bảng điều khiển quản trị.",
  eyebrow: "Trung tâm quản trị EDUcare",
  title: "Quản lý nội dung, ngân hàng quiz và trò chơi",
  description: "Chọn danh mục, cập nhật nội dung nhanh và lưu thay đổi trực tiếp trên hệ thống.",
  createNew: "Tạo mới",
  sections: {
    management: "Danh mục quản lý",
    selectArea: "Chọn khu vực",
  },
  stats: {
    users: "Người dùng",
    lessons: "Bài học",
    quizBank: "Ngân hàng quiz",
    games: "Trò chơi",
  },
  tabs: {
    lessons: "Khóa học",
    blogPosts: "Bài viết",
    quizQuestions: "Ngân hàng quiz",
    games: "Trò chơi",
  },
  list: {
    lessons: "Danh sách bài học",
    blogPosts: "Danh sách bài viết",
    quizQuestions: "Ngân hàng câu hỏi",
    games: "Danh sách trò chơi",
  },
  editor: {
    lessons: "Biên tập bài học",
    blogPosts: "Biên tập bài viết",
    quizQuestions: "Biên tập câu hỏi quiz",
    games: "Biên tập trò chơi",
  },
  titles: {
    updateLesson: "Cập nhật bài học",
    createLesson: "Tạo bài học mới",
    updateBlogPost: "Cập nhật bài viết",
    createBlogPost: "Tạo bài viết mới",
    updateQuizQuestion: "Cập nhật câu hỏi",
    createQuizQuestion: "Thêm câu hỏi mới",
    updateGame: "Cập nhật trò chơi",
    createGame: "Thêm trò chơi mới",
  },
  actions: {
    save: "Lưu",
    delete: "Xóa",
    saving: "Đang lưu...",
    deleteSuccess: {
      lesson: "Đã xóa bài học.",
      blogPost: "Đã xóa bài viết.",
      quizQuestion: "Đã xóa câu hỏi quiz.",
      game: "Đã xóa trò chơi.",
    },
    saveSuccess: {
      lesson: "Đã lưu bài học.",
      blogPost: "Đã lưu bài viết.",
      quizQuestion: "Đã lưu câu hỏi quiz.",
      game: "Đã lưu trò chơi.",
    },
  },
  fields: {
    order: "Thứ tự",
    title: "Tiêu đề",
    shortDescription: "Mô tả ngắn",
    content: "Nội dung",
    freeAccess: "Cho phép học miễn phí",
    category: "Danh mục",
    publishDate: "Ngày đăng",
    readTimeMinutes: "Số phút đọc",
    emoji: "Biểu tượng",
    explanation: "Giải thích",
    difficulty: "Độ khó",
    correctAnswer: "Đáp án đúng",
    publishFrontend: "Hiển thị trên giao diện",
    gameType: "Loại game",
    playPath: "Đường dẫn chơi",
    summary: "Tóm tắt",
    accentColor: "Màu nhấn",
    coverImage: "Ảnh bìa",
    question: "Câu hỏi",
    option: "Lựa chọn",
    activeQuiz: "Cho phép load vào quiz",
  },
  defaults: {
    quizCategory: "Cảm xúc",
    quizDifficulty: "Cơ bản",
    blogEmoji: "Bài",
  },
  errors: {
    saveLesson: "Không thể lưu bài học.",
    deleteLesson: "Không thể xóa bài học.",
    saveBlogPost: "Không thể lưu bài viết.",
    deleteBlogPost: "Không thể xóa bài viết.",
    saveQuizQuestion: "Không thể lưu câu hỏi quiz.",
    deleteQuizQuestion: "Không thể xóa câu hỏi quiz.",
    saveGame: "Không thể lưu trò chơi.",
    deleteGame: "Không thể xóa trò chơi.",
  },
} as const;

export const FOOTER_COPY = {
  title: "Không gian học tập và chăm sóc tinh thần dành cho tuổi teen.",
  description:
    "EDUcare giúp các bạn trẻ hiểu hơn về cảm xúc, cơ thể và các mối quan hệ, đồng thời tạo ra một nơi nhẹ nhàng để đặt câu hỏi khi cần được hỗ trợ.",
  content: "Nội dung",
  community: "Cộng đồng",
  contact: "Liên hệ",
  supportNotice:
    "Nếu bạn đang thấy lo lắng kéo dài hoặc cần được lắng nghe ngay, hãy tìm đến người lớn đáng tin cậy để được hỗ trợ.",
  copyright: "© 2026 EDUcare. Đồng hành cùng tuổi teen trên hành trình lớn lên.",
} as const;

export const ANONYMOUS_QUESTION_COPY = {
  title: "Hộp thư ẩn danh",
  badge: "Ẩn danh",
  description:
    "Gửi câu hỏi về cảm xúc, sức khỏe tinh thần hoặc những điều khó nói để nhận phản hồi tham khảo trong một không gian kín đáo hơn.",
  success: "Câu hỏi ẩn danh đã được gửi.",
  sendError: "Không thể gửi câu hỏi.",
  loginToLike: "Đăng nhập để thích câu hỏi.",
  likeError: "Không thể thích câu hỏi.",
  questionPlaceholder: "Nhập câu hỏi của bạn...",
  loginPlaceholder: "Đăng nhập để gửi câu hỏi...",
  sentHint: "Câu hỏi đã được gửi ẩn danh. Bạn có thể xem phản hồi trong mục thông báo.",
  recentQuestions: (count: number) => `${count} câu hỏi gần đây`,
  answerPrefix: "Trả lời:",
} as const;
